export const ADD_GROCERY = "ADD_GROCERY";
export const REMOVE_GROCERY = "REMOVE_GROCERY";
export const CLEAR_GROCERY_LIST = "CLEAR_GROCERY_LIST";
export const EDIT_GROCERY = "EDIT_GROCERY";
export const PURCHASE_GROCERY = "PURCHASE_GROCERY";
